stage/administratief/views.py
from flask import Flask, Blueprint,render_template,redirect,url_for, flash
from flask_login import login_user, login_required, logout_user, current_user
from stage.models import RelationTable, Student, Bedrijf, db
from stage.administratief.forms import *


administratief_blueprint = Blueprint('administratief',
                              __name__,
                              template_folder='templates/')


# A page for administrators
# Checks if the current user is an administrator
# If yes, the user gets redirected to "index.html"
# If not, the user gets flashed a message
@administratief_blueprint.route("/" )

def administratief():
    return render_template("index.html")


# A page for administrators
# Checks if the current user is an administrator
# If yes, the user gets redirected to "stdnt_home.html"
# If not, the user gets flashed a message 
@administratief_blueprint.route("/student", methods=["GET", "POST"])

def administratief_student():
    return render_template("stdnt_home.html")


# A page for administrators
# Checks if the current user is an administrator
# If yes, the user gets redirected to "beg_home.html"
# If not, the user gets flashed a message 
@administratief_blueprint.route("/begeleider" , methods=["GET", "POST"])

def administratief_begeleider():
    return render_template("beg_home.html")


# A page for administrators
# Checks if the current user is an administrator
# If yes, the user gets redirected to "beg_home.html"
# If not, the user gets flashed a message 
@administratief_blueprint.route("/bedrijven" , methods=["GET", "POST"])

def administratief_bedrijven():
    return render_template("bedr_home.html")


# A page for administrators for adding students
@administratief_blueprint.route("/student/toevoegen", methods=["GET", "POST"])

def administratief_student_add():
    # Checks if the current user is an administrator
    # If yes the user can acces the page
    # If not the user gets flashed a message
    
    # Makes a form where you can select any of the existing "students" "bedrijven" or "begeleider"
    student = Student.query.all()
    bedrijven = Bedrijf.query.all()
    begeleider = Begeleider.query.all()
    form = Student_add() 
    form.student.choices = [x.voornaam for x in student]
    form.bedrijven.choices = [x.naam for x in bedrijven]
    form.begeleider.choices = [x.voornaam for x in begeleider]

    if form.validate_on_submit():
         #Filters on submitted data
        student = Student.query.filter_by(voornaam=form.student.data)
        bedrijf = Bedrijf.query.filter_by(naam=form.bedrijven.data)
        begeleider = Begeleider.query.filter_by(voornaam=form.begeleider.data)
        RelationTable_entry = RelationTable(student=student.first().id, bedrijf=bedrijf.first().id, begeleider=begeleider.first().id, cijfer=form.cijfer.data, periode=form.periode.data)
        db.session.add(RelationTable_entry)
        db.session.commit()
        
        flash("Stage is succesvol gekoppeld aan de student")
        return redirect(url_for("administratief.administratief"))
    return render_template("stdnt_add.html", form=form)


# A page for administrators for editing students
@administratief_blueprint.route("/student/bewerken", methods=["GET", "POST"])

def administratief_student_edit():
    # Checks if the current user is an administrator
    # If yes the user can acces the page
    
    # Makes a form where you can select any of the existing "stage" "bedrijven" or "begeleider"
    stage = RelationTable.query.all()
    bedrijven = Bedrijf.query.all()
    begeleider = Begeleider.query.all()
    form = Student_edit()
    form.student.choices = [x.Student.voornaam for x in stage]
    form.bedrijven.choices = [x.naam for x in bedrijven]
    form.begeleider.choices = [x.voornaam for x in begeleider]
    
    if form.validate_on_submit():
        # Filters on submitted data
        student = form.student.data
        id = RelationTable.query.filter_by(student=Student.query.filter_by(voornaam=student).first().id).first().id
        totaal = RelationTable.query.get(id)
        totaal.bedrijven = Bedrijf.query.filter_by(naam=form.bedrijven.data).first().id
        totaal.begeleider = Begeleider.query.filter_by(voornaam=form.begeleider.data).first().id
        totaal.cijfer = form.cijfer.data
        totaal.periode = form.periode.data
        db.session.commit()
        flash("Stage succesvol bewerkt")
        return redirect(url_for("administratief.administratief"))
    return render_template("stdnt_edit.html", form=form)


# A page for administrators for deleting students
@administratief_blueprint.route("/student/verwijderen", methods=["GET", "POST"])

def administratief_student_del():
    # Checks if the current user is an administrator
    # If yes the user can acces the page
    # If not the user gets flashed a message

    # Makes a form where you can select any of the existing "stage" 
    stage = RelationTable.query.all()
    form = Student_del()
    form.student.choices = [x.Student.voornaam for x in stage]

    if form.validate_on_submit():
        # Filters on submitted data
        student = form.student.data
        naam = RelationTable.query.filter_by(student=Student.query.filter_by(voornaam=student).first().id).first().id
        db.session.delete(RelationTable.query.get(naam))
        db.session.commit()
        flash("Gekoppelde stage succesvol verwijderd van student")
        return redirect(url_for("administratief.administratief"))
    
    totaal_list = []
    for x in stage:
        y = str(x).split('|')
        student= y[0]
        bedrijf = y[1]
        begeleider = y[2]
        cijfer = y[3]
        periode = y[4]
        totaal_list.append([student, bedrijf, begeleider, cijfer, periode])

    return render_template("stdnt_del.html", stages=totaal_list, form=form)


# A page for administrators for deleting students
@administratief_blueprint.route("/student/lijst", methods=["GET", "POST"])

def administratief_student_list():
    # Checks if the current user is an administrator
    # If yes the user can acces the page
    # If not the user gets flashed a message

    # Request all data from table RelationTable
    stage = RelationTable.query.all()
    
    totaal_list = []
    for x in stage:
        y = str(x).split('|')
        student= y[0]
        bedrijf = y[1]
        begeleider = y[2]
        cijfer = y[3]
        periode = y[4]
        totaal_list.append([student, bedrijf, begeleider, cijfer, periode])

    return render_template("stdnt_list.html", stages=totaal_list)


# A page for adding "begeleiders"
@administratief_blueprint.route("/begeleider/toevoegen", methods=["GET", "POST"])

def administratief_begeleider_add():
    
    # Makes a form where you can add a begeleider
    form = Begeleider_add()

    if form.validate_on_submit():
        # Filters on the submitted data
        begeleider = Begeleider(voornaam=form.voornaam.data, achternaam=form.achternaam.data)
        db.session.add(begeleider)
        db.session.commit()
        flash("Begeleider succesvol toegevoegd")
        return redirect(url_for("administratief.administratief"))
    return render_template("beg_add.html", form=form)

# A page for deleting "begeleiders"
@administratief_blueprint.route("/begeleider/verwijderen", methods=["GET", "POST"])

def administratief_begeleider_del():
    
    # Makes a form where you can select a begeleider to delete
    begeleiders = Begeleider.query.all()
    form = Begeleider_del()
    form.begeleider.choices = [x.voornaam for x in begeleiders]

    if form.validate_on_submit():
        # Filters on the submitted data
        voornaam = form.begeleider.data
        begeleider = Begeleider.query.filter_by(voornaam=voornaam).first().id
        db.session.delete(Begeleider.query.get(begeleider))
        db.session.commit()
        flash("Begeleider verwijdering succesvol voltooid!")
        return redirect(url_for("administratief.administratief"))

    return render_template("beg_del.html", begeleiders=begeleiders, form=form)


# A page for adding a company
@administratief_blueprint.route("/bedrijven/toevoegen", methods=["GET", "POST"])

def administratief_bedrijven_add():
    
    # Makes a form where you can add a company
    form = bedrijven_add()
    
    # Submits the given data
    if form.validate_on_submit():
        # Filters on the submitted data
        bedrijf = Bedrijf(naam=form.naam.data, soort=form.soort.data)
        db.session.add(bedrijf)
        db.session.commit()
        flash("Bedrijf succesvol toegevoegd!")
        return redirect(url_for("administratief.administratief"))
    return render_template("bedr_add.html", form=form)


# A pagefor deleting a company
@administratief_blueprint.route("/bedrijven/verwijderen", methods=["GET", "POST"])

def administratief_bedrijven_del():
    
    # Makes a form where you can select a company to delete
    bedrijven = Bedrijf.query.all()
    form = bedrijven_del()
    form.bedrijven.choices = [x.naam for x in bedrijven]
    
    # Submits the given data
    if form.validate_on_submit():
        naam = form.bedrijven.data
        bedrijf = Bedrijf.query.filter_by(naam=naam).first().id
        db.session.delete(Bedrijf.query.get(bedrijf))
        db.session.commit()
        flash("Bedrijf succesvol verwijderd!")
        return redirect(url_for("administratief.administratief"))
    return render_template("bedr_del.html", form=form, bedrijven=bedrijven)

stage/administratief/templates/bedr_add.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="d-flex justify-content-center" style='text-align: center'>

        <!-- Forms -->
        <form method="POST">
            <!-- Pagina titel -->
            <h1>Stageplek toevoegen</h1> <hr><br>
            {{form.hidden_tag()}}
            <div class='row'>
                <!-- Bedrijf naam label -->
                <div class="col-md-6">
                    <label class="form-label">{{form.naam.label}}</label>
                    <br>{{form.naam(class_="form-control")}}
                </div>
                <!-- Naam type label -->
                <div class="col-md-6">
                    <label class="form-label">{{form.soort.label}}</label>
                    <br>{{form.soort(class_="form-control")}}
                </div>
            </div>
            <br>
            <!-- Submit button -->
            {{form.submit()}}
        </form>
    </div>
</div>
{% endblock %}

stage/administratief/templates/bedr_del.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <div class="d-flex justify-content-center" style='text-align: center'>

    <!-- Form -->
    <form method="POST">
      <!-- Pagina title -->
      <h1>Stageplek Verwijderen</h1> <br>
      {{form.hidden_tag()}}
      <!-- Bedrijf label en knop -->
      {{form.bedrijven.label}}: {{form.bedrijven()}} {{form.submit()}}

      <!-- Informatie tabel -->
      <div class="container px-4">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th scope="col">Naam bedrijf: </th>
              <th scope="col">ICT/Marketing:</th>
            </tr>
          </thead>
          <tbody>
            {% for ins in bedrijven %}
            <tr>

              <td>{{ins.naam}} </td>
              <td>{{ins.soort}}</td>

            </tr>
            {% endfor %}

          </tbody>
        </table>
      </div>
    </form>

  </div>
</div>
{% endblock %}

stage/administratief/templates/beg_add.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="d-flex justify-content-center" style='text-align: center'>

        <!-- Form -->
        <form method="POST">
            <!-- Pagina titel -->
            <h1>Begeleider toevoegen</h1> <hr> <br>
            {{form.hidden_tag()}}
            <div class='row'>
                <!-- Voornaam form label-->
                <div class="col-md-6">
                    <label class="form-label">{{form.voornaam.label}}</label>
                    <br>{{form.voornaam()}}
                </div>
                <!-- Achternaam form label-->
                <div class="col-md-6">
                    <label class="form-label">{{form.achternaam.label}}</label>
                    <br>{{form.achternaam()}}
                </div>
            </div>
            
            <br>
            <!-- Submit knop -->
            {{form.submit()}}
        </form>
    </div>
</div>
{% endblock %}

stage/administratief/templates/beg_del.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="d-flex justify-content-center" style='text-align: center'>

        <!-- Form -->
        <form method="POST">
            <!-- Pagina titel -->
            <h1>Begeleider Verwijderen</h1><hr><br>
            {{form.hidden_tag()}}
            <!-- Label begeleider-->
            {{form.begeleider.label}}: {{form.begeleider()}} {{form.submit()}}
            <br>
            <br>
            <!-- laat verschillende begeleiders zien -->
            <div class="container">

                <table class="table table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Voornaam</th>
                            <th scope="col">Achternaam</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for beg in begeleiders %}
                        <tr>

                            <td>{{beg.voornaam}}</td>
                            <td>{{beg.achternaam}}</td>

                        </tr>
                        {% endfor %}

                    </tbody>
                </table>

            </div>
        </form>
    </div>

</div>
{% endblock %}

stage/administratief/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <center>
    <!-- Pagina titel-->
    <h1> Welkom Administrator!</h1>
    <br>
    <p> Op deze pagina kunt u nieuwe data toevoegen of verwijderen, daarnaast kunt u hier ook alle beschikbare data
      aanpassen.
    </p>
    <br>
    <div class="container">
      <!-- Kolommen -->

      <div class="card">
        <div class="card-header">
          Dashboard Studenten
        </div>
        <div class="card-body">
          <p class="card-text">Het toevoegen/verwijderen/bewerken van data bij Studenten, kunt u hieronder toepassen.
          </p>
          <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
            <a href='{{url_for('administratief.administratief_student_add') }}'>a</a>
            <label class="btn btn-outline-primary" for="btnradio1">Koppeling Student - Stage aanmaken</label>

            <a href='{{url_for('administratief.administratief_student_del') }}'>a</a>
            <label class="btn btn-outline-primary" for="btnradio2">Koppeling Student - Stage verwijderen</label>

            <a href='{{url_for('administratief.administratief_student_edit') }}'>a</a>
            <label class="btn btn-outline-primary" for="btnradio3">Koppeling Student - Stage bewerken</label>
          </div>
          <div class="card-body">
            <a href='{{url_for('administratief.administratief_student_list') }}'>a</a>
            <label class="btn btn-outline-primary" for="btnradio8">Alle studenten</label>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="container">

      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header">
              Dashboard Begeleiders
            </div>
            <div class="card-body">
              <p class="card-text">Het toevoegen/verwijderen van data bij Begeleiders, kunt u hieronder toepassen.</p>
              <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                <a href='{{url_for('administratief.administratief_begeleider_add') }}'>a</a>
                <label class="btn btn-outline-primary" for="btnradio4">Begeleider toevoegen</label>

                <a href='{{url_for('administratief.administratief_begeleider_del') }}'>a</a>
                <label class="btn btn-outline-primary" for="btnradio5">Begeleider verwijderen</label>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card">
            <div class="card-header">
              Dashboard Stageplekken
            </div>
            <div class="card-body">
              <p class="card-text">Het toevoegen/verwijderen van data bij Stageplekken, kunt u hieronder toepassen.</p>
              <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                <a href='{{url_for('administratief.administratief_bedrijven_add') }}'>a</a>
                <label class="btn btn-outline-primary" for="btnradio6">Stageplek toevoegen</label>

                <a href='{{url_for('administratief.administratief_bedrijven_del') }}'>a</a>
                <label class="btn btn-outline-primary" for="btnradio7">Stageplek verwijderen</label>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>


  </center>
</div>
{% endblock %}

stage/administratief/templates/stdnt_add.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="d-flex justify-content-center" style='text-align: center'>

        <!-- Form -->
        <form method="POST">
            <h1>Student toevoegen aan stage/bedrijf</h1><br>
            <h3>Bedrijf & Begeleider</h3>
            <hr>
            {{form.hidden_tag()}}
            <!-- Form Student label-->
            {{form.student.label}}: {{form.student()}} <br>
            <!-- Form bedrijven label-->
            {{form.bedrijven.label}}: {{form.bedrijven()}} <br>
            <!-- Form begeleider label-->
            {{form.begeleider.label}}: {{form.begeleider()}} <br><br>
            <h3>Cijfer & Periode</h3>
            <hr>
            <div class='row'>
                <div class="col-md-6">
                    <label class="form-label">{{form.cijfer.label}}</label>
                    <br>{{form.cijfer()}}
                    <small>
                        <p class="card-text">bijv: 7</p>
                    </small>
                </div>
                <div class="col-md-6">
                    <label class="form-label">{{form.periode.label}}</label>
                    <br>{{form.periode()}}
                    <small>
                        <p class="card-text">bijv: sem. 1 2021</p>
                    </small>
                </div>
            </div>
            <!-- Submit knop-->
            <br>
            {{form.submit()}}
        </form>
    </div>
</div>
{% endblock %}

stage/administratief/templates/stdnt_del.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="d-flex justify-content-center" style='text-align: center'>

        <!-- Form -->
        <form method="POST">
            <!-- Pagina titel -->
            <h1>Koppeling Student - Stage verwijderen</h1> <br>

            {{form.hidden_tag()}}
            <!-- Form Student label -->
            {{form.student.label}}: {{form.student()}} {{form.submit()}}

            <!-- Tabel -->
            <div class="container">

                <table class="table table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Student</th>
                            <th scope="col">Bedrijf</th>
                            <th scope="col">Begeleider</th>
                            <th scope="col">Cijfer</th>
                            <th scope="col">Periode</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for stage in stages %}
                        <tr>

                            <td>{{stage[0]}}</td>
                            <td>{{stage[1]}}</td>
                            <td>{{stage[2]}}</td>
                            <td>{{stage[3]}}</td>
                            <td>{{stage[4]}}</td>

                        </tr>
                        {% endfor %}

                    </tbody>
                </table>

            </div>
        </form>
    </div>
</div>
{% endblock %}

stage/administratief/templates/stdnt_edit.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="d-flex justify-content-center" style='text-align: center'>

        <!-- Form -->
        <form method="POST">
            <h1>Koppelingen van student bewerken</h1><br>
            <h3>Bedrijf & Begeleider</h3>
            <hr>
            {{form.hidden_tag()}}
            <!-- Form Student label-->
            {{form.student.label}}: {{form.student()}} <br>
            <!-- Form bedrijven label-->
            {{form.bedrijven.label}}: {{form.bedrijven()}} <br>
            <!-- Form begeleider label-->
            {{form.begeleider.label}}: {{form.begeleider()}} <br><br>
            <h3>Cijfer & Periode</h3>
            <hr>
            <div class='row'>
                <div class="col-md-6">
                    <label class="form-label">{{form.cijfer.label}}</label>
                    <br>{{form.cijfer()}}
                    <small>
                        <p class="card-text">bijv: 7</p>
                    </small>
                </div>
                <div class="col-md-6">
                    <label class="form-label">{{form.periode.label}}</label>
                    <br>{{form.periode()}}
                    <small>
                        <p class="card-text">bijv: sem. 1 2021</p>
                    </small>
                </div>
            </div>
            <!-- Submit knop-->
            <br>
            {{form.submit()}}
        </form>
    </div>
</div>
{% endblock %}

stage/administratief/templates/stdnt_list.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="d-flex justify-content-center" style='text-align: center'>

        <!-- Form -->
        <form method="POST">
            <!-- Pagina titel -->
            <h1>Studenten - Stage lijst</h1> <br>

            <!-- Tabel -->
            <div class="container">

                <table class="table table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Student</th>
                            <th scope="col">Bedrijf</th>
                            <th scope="col">Begeleider</th>
                            <th scope="col">Cijfer</th>
                            <th scope="col">Periode</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for stage in stages %}
                        <tr>

                            <td>{{stage[0]}}</td>
                            <td>{{stage[1]}}</td>
                            <td>{{stage[2]}}</td>
                            <td>{{stage[3]}}</td>
                            <td>{{stage[4]}}</td>

                        </tr>
                        {% endfor %}

                    </tbody>
                </table>

            </div>
        </form>
    </div>
</div>
{% endblock %}