stage/stage/views.py
from flask import Flask, Blueprint,render_template,redirect,url_for, flash
from flask_login import login_user, login_required, logout_user, current_user
from stage.models import *
from stage.forms import *


stage_blueprint = Blueprint('stage',
                              __name__,
                              template_folder='templates/')


# Sends you to the stageplekken page
@stage_blueprint.route("/")
def stages():

    # Shows the corresponding stageplek of the user
    stage = RelationTable.query.all()
    bedrijf = Bedrijf.query.all()

    if current_user.is_authenticated:

        # Filters on the given data
        id = RelationTable.query.filter_by(student=current_user.student_nr).first()
        if id:
            User_data = []
            user = RelationTable.query.get(id.id)
            x = str(user).split('|')
            student= x[0]
            bedrijf = x[1]
            begeleider = x[2]
            cijfer = x[3]
            periode = x[4]
            User_data.append([student, bedrijf, begeleider, cijfer, periode])
            return render_template("stage.html", bedrijf=bedrijf, stage=stage, totaal=User_data[0])
    return render_template("stage.html", bedrijf=bedrijf, stage=stage)

stage/templates/base.html
<!DOCTYPE html>
<html>

<!-- Header -->

<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>

  <meta charset="utf-8">
  <title>HBO-Stage</title>
  <!-- Google Font -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>

<!-- Jumbotron implementatie -->
<style>
  .jumbotron {
    padding: 2rem 1rem;
    background-color: #e9ecef;
    border-radius: .3rem;
  }
</style>

<!-- Body -->

<body>

  <!--  Navigatiebalk  -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('home') }}">HBO-Stage</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">

          <!-- Gebruiker ingelogd-->
          {% if current_user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="material-icons">account_circle</i> Profiel
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

              <!-- Admin -->
              {% if current_user.admin == "1" %}
              <big class="dropdown-item"><b>{{current_user.username}}</b></big>
              <a class="dropdown-item" href="{{url_for('administratief.administratief') }}">Administratie</a>
              {% else %}
              <big class="dropdown-item"><b>{{current_user.username}}</b></big>
              <a class="dropdown-item" href="{{url_for('stage.stages') }}"> Informatie Stageplek</a>
              {% endif %}

            </div>
          </li>
          {% else %}
          <a class="nav-link" href="{{ url_for('stage.stages') }}">Stageplekken</a>
          {% endif %}
        </div>
      </div>

    </div>
    </div>
    </div>
    {% if not current_user.is_authenticated %}
    <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
      <input onclick="window.location.href='{{ url_for('login') }}'" type="radio" class="btn-check btn-success"
        name="btnradio" id="btnradio1" autocomplete="off">
      <label class="btn btn-outline-primary" for="btnradio1">Inloggen</label>

      <input onclick="window.location.href='{{ url_for('register') }}'" type="radio" class="btn-check " name="btnradio"
        id="btnradio2" autocomplete="off">
      <label class="btn btn-outline-primary" for="btnradio2">Registeren</label>
    </div>
    {% endif %}
    {% if current_user.is_authenticated %}
    <button class="btn btn-outline-danger me-2" onclick="location.href='{{url_for('logout') }}';"
      type="button">Uitloggen</button>
    {% endif %}
  </nav>

  <body>
    {% for message in get_flashed_messages()  %}
    <div class="jumbotron">
      <div class="alert alert-info alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

    </div>
    {% endfor %}
    {% block content %}

    {% endblock %}
  </body>

</html>

stage/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="d-flex justify-content-center" style='text-align: center'>

        <section class="py-5 text-center container">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">HBO-Stage</h1>
                <p class="lead text-muted">Op deze website kunt u alle informatie vinden over uw stage.<br>Daarnaast
                    kunt u alle beschikbare stageplekken vinden onder het tabblad 'Stageplekken'.</p>
                {% if not current_user.is_authenticated %}
                <p class="lead text-muted">
                    Heeft u nog geen account?</p>
                <p class="lead text-muted">Klik <a href="{{ url_for('register') }}">hier</a> om u te registreren</p>
                <p class="lead text-muted">Klik <a href="{{ url_for('login') }}">hier</a> om u te login</p>
                <p> Klik <a href="{{url_for('administratief.administratief') }}">hier</a> om direct naar het
                    administratie paneel te gaan.</p>
                {% else %}
                <br>
                <hr>
                <p class="lead">Welkom terug {{current_user.username}}!</p>

                {% endif %}
            </div>
        </section>

    </div>
</div>
{% endblock %}

stage/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="d-flex justify-content-center" style='text-align: center'>
        <!-- Form -->
        <form method="POST">
            <!--Titel -->
            <br>
            <h1 class="card-title">Inloggen</h1>
            <hr>
            {{form.hidden_tag()}}
            <!-- Username label -->
            <div class="col-md-6">
                <label for="inputEmail4" class="form-label">{{form.username.label}}</label>
                <br>{{form.username()}}
            </div>
            <!-- Password label -->
            <div class="col-md-6">
                <label for="inputPassword4" class="form-label">{{form.password.label}}</label>
                <br>{{form.password()}}
            </div>
            <hr>
            <!-- Knop -->
            <div class="col-12">
                {{form.submit()}}
            </div>
        </form>
        <form>
    </div>
</div>
{% endblock %}

stage/templates/register.html
{% extends "base.html"%}
{% block content %}
<div class="jumbotron">
    <div class="d-flex justify-content-center" style='text-align: center'>

        <form method="POST">
            <!-- Titel -->
            <h1 class="card-title"> Registreren </h1>
            <hr>
            {{form.hidden_tag()}}
            <!--Voornaamlabel-->
            <div class="row">
                <div class="col-md-6">
                    <label class="form-label">{{form.voornaam.label}}*</label>
                    <br>{{form.voornaam(class_="form-control", placeholder="Voornaam")}}
                </div>
                <div class="col-md-6">
                    <!--achternaamlabel-->
                    <label class="form-label">{{form.achternaam.label}}*</label>
                    <br>{{form.achternaam(class_="form-control", placeholder="Achternaam")}}
                </div>
            </div>
            <hr>
            <!--emaillabel-->
            <div class="row">
                <div class="col-md-6">
                    <label for="inputEmail4" class="form-label">{{form.email.label}}*</label>
                    <br>{{form.email(class_="form-control", placeholder="E-mailadres")}}
                </div>
                <div class="col-md-6">
                    <!--usernamelabel -->
                    <label class="form-label">{{form.username.label}}*</label>
                    <br>{{form.username(class_="form-control", placeholder="Gebruikersnaam")}}

                </div>
            </div>
            <hr>
            <!--wachtwoordlabel-->
            <div class="row">
                <div class="col-md-6">
                    <label class="form-label">{{form.password.label}}*</label>
                    <br>{{form.password(class_="form-control", placeholder="Wachtwoord")}}
                </div>
                <div class="col-md-6">
                    <!--wachtwoordlabel-->
                    <label class="form-label">{{form.pass_confirm.label}}*</label>
                    <br>{{form.pass_confirm(class_="form-control", placeholder="Bevestig Wachtwoord")}}
                </div>
            </div>
            <hr>
            <!--Knop -->
            {{form.submit()}}
        </form>
    </div>
</div>
{% endblock %}